{
 "title": "Logs Centralisés - Digital Factory",
 "tags": [
  "monitoring",
  "loki",
  "cires"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Source", "query": "loki" },
   { "name": "service", "label": "Service", "query": "label_values(service_name)" },
   { "name": "search", "label": "Recherche" }
  ]
 },
 "panels": [
  {
   "title": "Logs pour le service: $service",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"school-service\"}"
    }
   ]
  },
  {
   "title": "Volume de Logs par Niveau",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (severity_text) (count_over_time({service_name=\"school-service\"}[1m]))"
    }
   ]
  },
  {
   "title": "Volume d'error",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"school-service\"} | severity_text =~ \"ERROR|SEVERE\" [5m]))"
    }
   ]
  }
 ]
}